easy_admin:
    site_name: 'Basica - Back Office'

    entities:
#         List the entity class name you want to manage
        Post:
            class: App\Entity\Post
        Page:
            class: App\Entity\Page
        Category:
            class: App\Entity\Category
        Client:
            class: App\Entity\Client
        Tag:
            class: App\Entity\Tag
        User:
            class: App\Entity\User
        Work:
            class: App\Entity\Work

    design:
        menu:
          - { entity: 'Post', default: true }
          - Work
          - Tag
          - Category
