easy_admin:
    site_name: 'Basica - Back Office'

    entities:
#         List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            form:
                fields:
                    - {property: 'nomfr'}
                    - {property: 'nomen'}
                    - {property: 'titreonefr', type: 'text'}
                    - {property: 'texteonefr', type: 'fos_ckeditor'}
                    - {property: 'titreoneen', type: 'text'}
                    - {property: 'texteoneen', type: 'fos_ckeditor'}
                    - {property: 'titretwofr', type: 'text'}
                    - {property: 'textetwofr', type: 'fos_ckeditor'}
                    - {property: 'titretwoen', type: 'text'}
                    - {property: 'textetwoen', type: 'fos_ckeditor'}
                    - {property: 'categories'}
                    - { property: 'imageFile', type: 'vich_image'}
            list:
                fields:
                  - {property: 'id'}
                  - {property: 'nomfr'}
                  - {property: 'nomen'}
                  - {property: 'date'}
                  - {property: 'categories'}

        Page:
            class: App\Entity\Page
        Category:
            class: App\Entity\Category
            list:
                fields:
                  - {property: 'id'}
                  - {property: 'nomfr'}
                  - {property: 'nomen'}
        Client:
            class: App\Entity\Client
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                  - {property: 'id'}
                  - {property: 'nomfr'}
                  - {property: 'nomen'}
        User:
            class: App\Entity\User
        Work:
            class: App\Entity\Work
            list:
                fields:
                    - {property: 'nomfr'}
                    - {property: 'nomen'}
                    - {property: 'date'}
                    - {property: 'vitrine'}
                    - {property: 'client'}
                    - {property: 'tags'}
            form:
                fields:
                    - {property: 'nomfr'}
                    - {property: 'textefr', type: 'fos_ckeditor'}
                    - {property: 'nomen'}
                    - {property: 'texteen', type: 'fos_ckeditor'}
                    - {property: 'vitrine'}
                    - { property: 'imageFile', type: 'vich_image'}
                    - {property: 'client'}
                    - {property: 'tags'}

    design:
        brand_color: '#AEC62C'
        menu:
          - { entity: 'Post', default: true }
          - Work
          - Tag
          - Category
          - Client
