# Route par défaut: app_homepage
#   /
#   > showAction du PageController
#   Je suis sur le détail de la page 1
app_homepage:
    path: /{_locale}
    controller: App\Controller\PageController::showAction
    defaults:
        id: 1
        _locale: fr
    requirements:
        _locale: fr|en

# Route des pages
app_pages:
    resource: "Routes/pages.yaml"
    prefix: /pages
    name_prefix: app_pages_

# Route des works
app_works:
    resource: "Routes/works.yaml"
    prefix: /works
    name_prefix: app_works_

# Route des posts
app_posts:
    resource: "Routes/posts.yaml"
    prefix: /posts
    name_prefix: app_posts_

# Route des tags
app_tags:
    resource: "Routes/tags.yaml"
    prefix: /tags
    name_prefix: app_tags_

# Route des categories
app_categorys:
    resource: "Routes/categorys.yaml"
    prefix: /categorys
    name_prefix: app_categorys_
